BoECShop/urls.py
from django.urls import path, include

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('add_quantity/<product_id>', views.cart_add_quantity, name='cart_add_quantity'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),

]

orders/urls.py
from django.urls import path
from . import views

app_name='orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('process', views.order_save, name='order_save'),
    path('order_change_state/<order_id>', views.order_change_state, name='order_change_state'),
    path('admin/check_order', views.check_order, name='check_order'),
    path('remove/<order_id>', views.order_remove, name='order_remove'),
    path('comment/<order_id>', views.order_comment, name='order_comment'),
    path('detail/<order_id>', views.order_detail, name='order_detail'),
    path('', views.order_list, name='order_list'),  
]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search', views.product_search, name='product_search'),
    path('<category_slug>', views.product_list, name='product_list_by_category'),
    path('<id>/<slug>', views.product_detail, name='product_detail'),
]

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from shop.models import Product
from accounts.models import User


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'cart of {}'.format(self.user.email)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.product.name)

    def get_cost(self):
        return self.product.price * self.quantity

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.contrib.auth.decorators import login_required


@login_required
def cart_add(request, product_id):
    cart, created = Cart.objects.update_or_create(user=request.user)
    product = get_object_or_404(Product, id=product_id)
    item, itemCreated = CartItem.objects.update_or_create(
        cart=cart, product=product)

    if(itemCreated == False):
        item.quantity = item.quantity+1

    cart.items.add(item)
    item.save()
    cart.save()
    return redirect('cart:cart_detail')


@login_required
def cart_add_quantity(request, product_id, product_qty=None):
    cart, created = Cart.objects.update_or_create(user=request.user)
    product = get_object_or_404(Product, id=product_id)
    item, itemCreated = CartItem.objects.update_or_create(
        cart=cart, product=product)

    item.quantity = request.GET['quantity']
    if request.GET['quantity'] == "0":
        item.delete()
    else:
        cart.items.add(item)
        item.save()
        cart.save()
    return redirect('cart:cart_detail')


@login_required
def cart_remove(request, product_id):
    cart, created = Cart.objects.update_or_create(user=request.user)
    product = get_object_or_404(Product, id=product_id)
    cartItems = CartItem.objects.filter(cart=cart, product=product)
    cartItems.delete()
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    cart, created = Cart.objects.update_or_create(user=request.user)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Giỏ hàng
{% endblock %}

{% block content %}

&nbsp

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<table id="cart" class="table table-hover table-condensed">
	<thead>
		<tr>
			<th style="width:50%">Sản phẩm</th>
			<th style="width:10%" class="text-center">Giá</th>
			<th style="width:8%" class="text-center">Số lượng</th>
			<th style="width:22%" class="text-center">Thành tiền</th>
			<th style="width:10%"></th>
		</tr>
	</thead>

	<tbody>
		{% for item in cart.items.all %}
		{% with product=item.product %}
		<tr>
			<td data-th="Product">
				<div class="row">
					<div class="col-sm-2 hidden-xs">
						<a href='{% url "shop:product_detail" product.id product.slug %}'>
							<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="img-responsive">
						</a>
					</div>
					<div class="col-sm-10">
						<h4 class="nomargin">{{ product.name }}</h4>
						<p>{{ product.descripion }}</p>
					</div>
				</div>
			</td>
			<td data-th="Price" class="text-center">{{ product.price }} đ</td>
			<td data-th="Quantity" class="text-center">

				<form action="{% url 'cart:cart_add_quantity' product.id  %}">
					{% csrf_token %}
					<input type="number" name="quantity" value="{{ item.quantity }}" class="form-control text-center" 
					onchange="this.form.submit()">	
				</form>

			</td>
			<td data-th="Subtotal" class="text-center">{{item.get_cost}} đ</td>
			<td class="actions" data-th="">
				<a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-danger btn-sm">
					<i class="fa fa-trash-o"></i>
				</a>								
			</td>
		</tr>
		{% endwith %}
		{% endfor %}
	</tbody>

	<tfoot>
		<tr class="visible-xs">
			<td class="text-center"><strong>Giỏ hàng</strong></td>
		</tr>
		<tr>
			<td><a href="{% url 'shop:product_list' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Tiếp tục mua sắm</a></td>
			<td colspan="2" class="hidden-xs"></td>
			{% if cart.items.all %}
			<td class="hidden-xs text-center"><strong>Tổng tiền {{cart.get_total_cost}} đ</strong></td>
			<td><a href="{% url 'orders:order_create' %}" class="btn btn-success btn-block">Thanh toán <i class="fa fa-angle-right"></i></a></td>
			{% endif %}
		</tr>

	</tfoot>
</table>

&nbsp
{% endblock %}