BoECShop/urls.py
from django.urls import path, include

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup', views.signup, name='signup'),
    path('detail_profile', views.detail_profile, name='detail_profile')
]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('add_quantity/<product_id>', views.cart_add_quantity, name='cart_add_quantity'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),

]

orders/urls.py
from django.urls import path
from . import views

app_name='orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('process', views.order_save, name='order_save'),
    path('order_change_state/<order_id>', views.order_change_state, name='order_change_state'),
    path('admin/check_order', views.check_order, name='check_order'),
    path('remove/<order_id>', views.order_remove, name='order_remove'),
    path('comment/<order_id>', views.order_comment, name='order_comment'),
    path('detail/<order_id>', views.order_detail, name='order_detail'),
    path('', views.order_list, name='order_list'),  
]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search', views.product_search, name='product_search'),
    path('<category_slug>', views.product_list, name='product_list_by_category'),
    path('<id>/<slug>', views.product_detail, name='product_detail'),
]

wishlist/urls.py
from django.urls import path
from wishlist import views

app_name = 'wishlist'

urlpatterns = [

    path('add/<product_id>', views.wishlist_add, name='wishlist_add'),
    path('remove/<product_id>', views.wishlist_remove, name='wishlist_remove'),
    path('', views.wishlist_detail, name='wishlist_detail')

]

shop/models.py
from __future__ import unicode_literals
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    short_description = models.TextField(blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        index_together = (('id', 'slug'))

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from shop.models import Category, Product
from comment.models import Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    page = request.GET.get('page')
    paginator = Paginator(products, 6)
    try:
        products = paginator.page(page)

    except PageNotAnInteger:
        products = paginator.page(1)

    except EmptyPage:
        products = paginator.page(1)

    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
        }
    )


def product_search(request):
    categories = Category.objects.all()
    results = None
    key = request.POST['key']
    results = Product.objects.filter(name__icontains=key) |\
    Product.objects.filter(description__icontains=key)
    page = request.GET.get('page')
    paginator = Paginator(results, 6)
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(1)

    return render(
        request,
        'shop/product/list.html',
        {'categories': categories, 'products': results, 'key': key}
    )


def product_detail(request, id, slug):

    product = Product.objects.get(id = id, slug = slug, available=True)
    comments = Comment.objects.filter(product = product)

    return render(
        request,
        'shop/product/detail.html',
        {'product': product, 'comments': comments}
    )

templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}BoEC shop{% endblock %}</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/jquery/custom.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- Custom styles for this template -->
  <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-default navbar-fixed-top">

    <div class="container">
      <a href="/" style="text-decoration: none; color: black;"> 
        Nek Shop 
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse ml-5" id="navbarResponsive">
        <ul class="nav nav-pills">
        <li class="nav-item"><a href='{% url "shop:product_list" %}' class="nav-link">Tất cả</a></li>
        {% for c in categories %}
      <li class="nav-item"><a href='{% url "shop:product_list_by_category" c.slug %}' class="nav-link">{{ c.name }}</a></li>
      {% endfor %}
      <form action='{% url "shop:product_search" %}' method="post" class="ml-auto">
          {% csrf_token %}
          <div class="input-group h-100">
            <input type="text" name="key" class="form-control h-100" placeholder="Tìm kiếm theo tên..." required>
            <span class="input-group-btn">
              <button class="btn btn-default h-100" type="submit">Tìm</button>
            </span>
          </div><!-- /input-group -->
        </form>
              

      
                  {% if user.is_authenticated %}

          <li class="dropdown ml-3">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user.profile.full_name }}
            </a>

            <ul class="dropdown-menu ml-auto">
              <li>
                <a href="{% url 'accounts:detail_profile' %}" >
                  <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Thông tin cá nhân
                </a>
              </li>
              {% if user.is_staff %}
              <li>
                <a href="{% url 'admin:index' %}" >
                  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Trang quản lý
                </a>
              </li>
              <li>
                <a href="{% url 'orders:check_order' %}">
                  <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Kiểm tra đơn hàng
                </a>
              </li>
              {% else %}
              <li>
                <a href="{% url 'cart:cart_detail' %}">
                  <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Giỏ hàng
                </a>
              </li>
              <li>
                <a href="{% url 'wishlist:wishlist_detail' %}">
                  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Yêu thích
                </a>
              </li>
              <li>
                <a href="{% url 'orders:order_list' %}">
                  <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span> Theo dõi đơn hàng
                </a>
              </li>
              {% endif %}

              <li role="separator" class="divider"></li>

              <li>
                <a href="{% url 'accounts:logout' %}?next=/">
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Đăng xuất
                </a>
              </li>
            </ul>
          </li>

          {% else %}
          <li class="nav-item">
            <a href="{% url 'accounts:signup' %}" class="nav-link">
              <span aria-hidden="true"></span>&nbsp; Đăng kí
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="nav-link">
              <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; Đăng nhập
            </a>
          </li>

          {% endif %}
      </ul>
      </div>
    </div>
  </nav>
  &nbsp;
  <!-- Page Content -->
  <div class="container">
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- /.container -->
  &nbsp;

</body>
</html>