BoECShop/urls.py
from django.urls import path, include

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('add_quantity/<product_id>', views.cart_add_quantity, name='cart_add_quantity'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),

]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search', views.product_search, name='product_search'),
    path('<category_slug>', views.product_list, name='product_list_by_category'),
    path('<id>/<slug>', views.product_detail, name='product_detail'),
]

wishlist/urls.py
from django.urls import path
from wishlist import views

app_name = 'wishlist'

urlpatterns = [

    path('add/<product_id>', views.wishlist_add, name='wishlist_add'),
    path('remove/<product_id>', views.wishlist_remove, name='wishlist_remove'),
    path('', views.wishlist_detail, name='wishlist_detail')

]

shop/models.py
from __future__ import unicode_literals
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    short_description = models.TextField(blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
        index_together = (('id', 'slug'))

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from shop.models import Category, Product
from comment.models import Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    page = request.GET.get('page')
    paginator = Paginator(products, 6)
    try:
        products = paginator.page(page)

    except PageNotAnInteger:
        products = paginator.page(1)

    except EmptyPage:
        products = paginator.page(1)

    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
        }
    )


def product_search(request):
    categories = Category.objects.all()
    results = None
    key = request.POST['key']
    results = Product.objects.filter(name__icontains=key) |\
    Product.objects.filter(description__icontains=key)
    page = request.GET.get('page')
    paginator = Paginator(results, 6)
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(1)

    return render(
        request,
        'shop/product/list.html',
        {'categories': categories, 'products': results, 'key': key}
    )


def product_detail(request, id, slug):

    product = Product.objects.get(id = id, slug = slug, available=True)
    comments = Comment.objects.filter(product = product)

    return render(
        request,
        'shop/product/detail.html',
        {'product': product, 'comments': comments}
    )

templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="card mt-4">
      <div class="card-body">
        <img src='{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}' class="card-img-top img-fluid">  
      </div> <!-- /.card -->
    </div>
    &nbsp
    &nbsp
  </div>
  <div class="col-lg-4">
    <div class="card mt-4">
      <div class="card-body">
        <h2 class="my-4">
          <a style=" text-decoration: none;" href="{% url 'shop:product_list_by_category' product.category.slug %}">Liên quan: {{ product.category }}</a>
        </h2>
      </div>
    </div>
    <div class="card mt-4">
      <div class="card-body">
        <h3 class="card-title">{{ product.name }}</h3>
        <h4>{{ product.price }} đ</h4>
        <p class="card-text">{{ product.description|linebreaks }}</p>
        <div class="card-footer text-center">
          <small class="text-muted form-group " >
            <a href="{% url 'cart:cart_add' product.id %}" class="btn btn-success">Thêm vào giỏ</a>
            <a href="{% url 'wishlist:wishlist_add' product.id %}" class="btn btn-default">Yêu thích</a>
          </small>
        </div>
      </div>
    </div>
  </div>
</div>
&nbsp;
<div class="panel panel-info">
  <div class="panel-heading">
    <h2 class="panel-title">Các bình luận về sản phẩm</h3>
  </div>
  {% for comment in comments %}
  {% with user_comment=comment.user %}
  <div class="panel-body border-bottom">
    <p style="margin-bottom: 5px;">{{ user_comment.profile.full_name }}: {{ comment.content }}</p>
    <small>{{ comment.created }}</small>
  </div>

  {% endwith %}
  {% endfor %}
</div>
{% endblock %}

templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Trang chủ{% endif %}
{% endblock %}

{% block content %}

    <div class="row">
      <h3 class="my-4">
        {% if category %}{{ category.name }}
        {% elif key %}Tìm kiếm sản phẩm có từ khoá: {{ key }}
        {% else %}Tất cả sản phẩm
        {% endif %}
      </h3>
    </div>
    <div class="row">

      {% for product in products %}
      <div class="col-lg-3 col-md-6 mb-4">

        <div class="card h-100">
          <div class="thumbnail">
            <a href='{% url "shop:product_detail" product.id product.slug %}'>
              <img class="card-img-top px-5" src='{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}'>
            </a>
          </div>
          <div class="card-body">
            <h4 class="card-title text-center">
              <a href='{% url "shop:product_detail" product.id product.slug %}'>{{ product.name }}</a>
            </h4>
            <h5 class="text-danger text-center">{{ product.price }} đ</h5>
            <h5>{{ product.short_description }}</h5>
          </div>
          <div class="card-footer text-center">
            <small class="text-muted">
              <a href="{% url 'cart:cart_add' product.id %}" class="btn btn-success">Thêm vào giỏ</a>
              <a href="{% url 'wishlist:wishlist_add' product.id %}" class="btn btn-default">Yêu thích</a>
            </small>
          </div>

        </div>
      </div>
      {% endfor %}    
    </div><!-- /.row -->
  </div>


<div class="row">
  <div class="col-md-12 text-center">

    <div class="pag_area">
      <ul class="pagination">
        {% if products.has_previous %}
        <li><a href="?page={{ products.previous_page_number }}">«</a></li>
        {% else %}
        <li class="disabled"><span>«</span></li>
        {% endif %}
        {% for i in products.paginator.page_range %}
        {% if products.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if products.has_next %}
        <li><a href="?page={{ products.next_page_number }}">»</a></li>
        {% else %}
        <li class="disabled"><span>»</span></li>
        {% endif %}
      </ul>
    </div>

  </div>
</div>

<!-- /.row -->

{% endblock %}