BoECShop/urls.py
from django.urls import path, include

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('', include('shop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('add_quantity/<product_id>', views.cart_add_quantity, name='cart_add_quantity'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),

]

comment/urls.py
from django.urls import path
from . import views

app_name='comment'

urlpatterns = [
    path('add/<product_id>/<order_id>', views.comment_save, name='comment_save'),

]

orders/urls.py
from django.urls import path
from . import views

app_name='orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('process', views.order_save, name='order_save'),
    path('order_change_state/<order_id>', views.order_change_state, name='order_change_state'),
    path('admin/check_order', views.check_order, name='check_order'),
    path('remove/<order_id>', views.order_remove, name='order_remove'),
    path('comment/<order_id>', views.order_comment, name='order_comment'),
    path('detail/<order_id>', views.order_detail, name='order_detail'),
    path('', views.order_list, name='order_list'),  
]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search', views.product_search, name='product_search'),
    path('<category_slug>', views.product_list, name='product_list_by_category'),
    path('<id>/<slug>', views.product_detail, name='product_detail'),
]

orders/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from shop.models import Product
from accounts.models import User
from decimal import Decimal


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True)
    address_second = models.CharField(max_length=250, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    PAYMENT_CHOICES = (('0', 'Thanh toán khi nhận hàng'), ('1', 'Thanh toán bằng paypal'))
    payment_type = models.CharField(max_length=1, choices=PAYMENT_CHOICES, blank=True, default='0')
    paid = models.BooleanField(default=False)
    STATE_CHOICES = (('0', 'Chờ xác nhận'), ('1', 'Đã xác nhận'), 
        ('2', 'Đang giao hàng'), ('3', 'Giao hàng thành công'), ('4', 'Huỷ'), ('5', 'Giao hàng thất bại'))
    state = models.CharField(max_length=1, choices=STATE_CHOICES, blank=True, default='0')
    shipment_name = models.CharField(max_length=50, null=True, blank=True, default='Giao hàng tiết kiệm')
    shipment_price = models.DecimalField(max_digits=6, decimal_places=0, null=True, blank=True, default=Decimal('10000'))

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {} {}'.format(self.user, self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all()) + self.shipment_price;


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    isComment = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.product.price * self.quantity

orders/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from .models import *
from cart.models import Cart
from comment.models import Comment
from payment.models import Shipment
from accounts.models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


@login_required
def order_save(request):
    order = Order.objects.create(user=request.user)
    cart = Cart.objects.get(user=request.user)

    for item in cart.items.all():
        orderItem, created = OrderItem.objects.update_or_create(
            order=order, product=item.product, quantity=item.quantity)
        order.items.add(orderItem)

    order.phone_number = request.POST['phone_number']
    order.address_second = request.POST['address_second']
    order.payment_type = request.POST['payment_type']
    shipment = Shipment.objects.get(id=request.POST['shipment_type'])
    order.shipment_name = shipment.name
    order.shipment_price = shipment.price
    order.save()
    cart.delete()

    if order.payment_type == "1":
        return redirect('../../payment/' + str(order.id) + '/process')
    else:
        return render(request, 'orders/order_success.html')


@login_required
def order_create(request):
    profile = get_object_or_404(Profile, user=request.user)
    cart = Cart.objects.get(user=request.user)
    shipment = Shipment.objects.all()

    return render(request, 'orders/order_form.html', {'cart': cart, 'profile': profile, 'shipment': shipment})


@login_required
def order_list(request):
    if not Order.objects.filter(user=request.user).exists():
        return render(request, 'orders/order_list.html', {'empty': "yes"})
    else:
        orders = Order.objects.filter(user=request.user)
        return render(request, 'orders/order_list.html', {'orders': orders})


@login_required
def order_remove(request, order_id):
    order, created = Order.objects.update_or_create(id=order_id)
    order.state = '4'
    order.save()

    return redirect('orders:order_list')


@login_required
def order_detail(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'orders/order_detail.html', {'order': order})


@login_required
def order_comment(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'orders/order_comment.html', {'order': order})


@user_passes_test(lambda u: u.is_superuser)
def check_order(request):
    orders = Order.objects.all()
    if not orders:
        return render(request, 'orders/order_list_admin.html', {'empty': "yes"})
    else:
        return render(request, 'orders/order_list_admin.html', {'orders': orders})


@login_required
def order_change_state(request, order_id):
    order = Order.objects.get(id=order_id)
    order.state = request.GET['order_state']
    if order.state == '3':
        order.paid = True
    order.save()
    return redirect('orders:check_order')

templates/orders/order_comment.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Chi tiết đơn hàng
{% endblock %}

{% block content %}

&nbsp;

{% if order.state == '3' %}
<h2 style="text-align: center;">Đánh giá sản phẩm</h2>
&nbsp;&nbsp;
<table id="cart" class="table table-hover table-condensed">
	<thead>
		<tr>
			<th style="width:40%">Sản phẩm</th>
			<th style="width:50%">Bình luận</th>
			<th style="width:10%"></th>
		</tr>
	</thead>

	<tbody>
		{% for item in order.items.all %}
		{% with product=item.product %}
		<tr>
			<td data-th="Product">
				<div class="row">
					<div class="col-sm-2 hidden-xs">
						<a href='{% url "shop:product_detail" product.id product.slug %}'>
							<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="img-responsive">
						</a>
					</div>
					<div class="col-sm-10">
						<h4 class="nomargin">{{ product.name }}</h4>
					</div>
				</div>
			</td>
			{% if not item.isComment %}
			<form action="{% url 'comment:comment_save' product.id order.id %}" method="post">
				{% csrf_token %}
				<td>
					<input style="width: 100%; height: 60px;" type="text" name="comment_content">
				</td>
				<td>
					<input type="submit" value="Gửi" style="width: 100%; height: 60px;">
				</td>
			</form>
			{% else %}
			<td>
				<h5>Đã đánh giá sản phẩm này!</h5>
			</td>
			<td></td>
			{% endif %}
		</tr>
		{% endwith %}
		{% endfor %}
	</tbody>
</table>
{% endif %}

&nbsp;
{% endblock %}

templates/orders/order_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Chi tiết đơn hàng
{% endblock %}

{% block content %}
&nbsp;
<table id="cart" class="table table-hover table-condensed">
	<thead>
		<tr>
			<th style="width:50%">Sản phẩm</th>
			<th style="width:18%" class="text-center">Giá</th>
			<th style="width:12%" class="text-center">Số lượng</th>
			<th style="width:20%" class="text-center">Thành tiền</th>
		</tr>
	</thead>

	<tbody>
		{% for item in order.items.all %}
		{% with product=item.product %}
		<tr>
			<td data-th="Product">
				<div class="row">
					<div class="col-sm-2 hidden-xs">
						<a href='{% url "shop:product_detail" product.id product.slug %}'>
							<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="img-responsive">
						</a>
					</div>
					<div class="col-sm-10">
						<h4 class="nomargin">{{ product.name }}</h4>
					</div>
				</div>
			</td>
			<td data-th="Price" class="text-center">{{ product.price }} đ</td>
			<td data-th="Quantity" class="text-center">{{ item.quantity }}</td>
			<td data-th="Subtotal" class="text-center">{{ item.get_cost }} đ</td>
		</tr>
		{% endwith %}
		{% endfor %}
		<tr>
			<td><h4>Đơn vị ship: {{ order.shipment_name }}</h4></td>
			<td></td>
			<td></td>
			<td class="text-center">{{ order.shipment_price }} đ</td>
		</tr>
	</tbody>

	<tfoot>
		<tr class="visible-xs"></tr>
		<tr>
			<td></td>
			<td colspan="2" class="hidden-xs"></td>
			{% if order.items.all %}
			<td class="hidden-xs text-center"><strong>Tổng tiền: {{order.get_total_cost}} đ</strong></td>
			<td></td>
			{% endif %}
		</tr>

	</tfoot>
</table>

&nbsp;
{% endblock %}

templates/orders/order_form.html
{% extends "shop/base.html" %}

{% block title %}
Đặt hàng
{% endblock %}

{%block content %}
<div class="row">
  <div class="col-md-8">
    <h4 class="mb-3">Thông tin người mua</h4>

    <form name = "form" action = "{% url 'orders:order_save' %}" method = "POST" class="needs-validation">
      {% csrf_token %}
      <div class="mb-3">
        <label for="fullName">Họ tên*</label>
        <input type="text" class="form-control" id="fullName" placeholder="" value="{{ profile.full_name }}" required>
      </div>

      <div class="mb-3">
        <label for="phone_number">Số điện thoại*</label>
        <input type="text" value="{{ profile.phone_number }}" name="phone_number" class="form-control" required>
      </div>

      <div class="mb-3">
        <label for="email">Email*</label>
        <input type="email" class="form-control" value="{{ profile.user.email }}" required>
      </div>

      <div class="mb-3">
        <label for="address">Địa chỉ*</label>
        <input type="text" value="{{ profile.address }}" name="address" class="form-control" required>
      </div>

      <div class="mb-3">
        <label for="address_second">Địa chỉ khác <span class="text-muted">(Tuỳ chọn)</span></label>
        <input name="address_second" type="text" class="form-control">
      </div>

      <div class="mb-3">
        <label for="payment_type">Hình thức thanh toán*</label>
        <select name="payment_type" class="form-control" style="height: 35px">
          <option value="0">Thanh toán khi nhận hàng</option>
          <option value="1">Thanh toán bằng paypal</option>
        </select>
      </div>

      <div class="mb-3">
        <label for="shipment_type">Đơn vị vận chuyển*</label>
        <select name="shipment_type" class="form-control" style="height: 35px">
          {% for ship in shipment %}
          <option value={{ ship.id }}>{{ ship }}</option>
          {% endfor %}
        </select>
      </div>

      <hr class="mb-4">
      <input class="btn btn-primary btn-lg btn-block" type="submit" value="Tiếp tục">
    </form>
  </div>

  <div class="col-md-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Đơn hàng</span>
      <span class="badge badge-secondary badge-pill">{{cart.items.count}}</span>
    </h4>
    <ul class="list-group mb-3">
      {% for item in cart.items.all %}
      {% with product=item.product %}

      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">{{ product.name }}</h6>

        </div>
        <span class="text-muted">{{ product.price }} X {{ item.quantity }} = {{ item.get_cost }} đ</span>
      </li>

      {% endwith %}
      {% endfor %}

      <li class="list-group-item d-flex justify-content-between">
        <span>Tổng cộng</span>
        <strong>{{cart.get_total_cost}} đ</strong>
      </li>
    </ul>

  </div>
</div>
{% endblock %}

templates/orders/order_list.html
{% extends "shop/base.html" %}

{% block title %}
Trạng thái đơn hàng
{% endblock %}

{%block content %}
&nbsp;
{% if empty %}
<h1>Bạn chưa đặt đơn hàng nào</h1>
{% else %}
<style>
  table {
    border-collapse: collapse;
    border-spacing: 0;
    width: 100%;
  }

  th, td {
    text-align: center;
    padding: 16px;
  }

  #myTable tr {
    border-bottom: 1px solid #ddd;
  }

  #myTable tr.header, #myTable tr:hover {
    background-color: #ccc;
  }
</style>

<table id="myTable">
  <tr class="header">
    <th>Ngày đặt đơn</th>
    <th>Số điện thoại</th>
    <th>Địa chỉ nhận 1</th>
    <th>Địa chỉ nhận 2</th>
    <th>Tổng tiền</th>
    <th>Hình thức thanh toán</th>
    <th>Tình trạng thanh toán</th>
    <th>Trạng thái đơn hàng</th>
    <th style="width: 5%"></th>
  </tr>

  {% for order in orders.all %}
  <tr>
    <td>{{ order.created }}</td>
    <td>{{ order.phone_number }}</td>
    <td>{{ order.user.profile.address }}</td>
    <td>{{ order.address_second }}</td>
    <td>{{ order.get_total_cost }} đ</td>
    <td>{% if order.payment_type == "1" %} Thanh toán bằng paypal {% else %} Thanh toán khi nhận hàng {% endif %}</td>
    <td>{% if order.paid %} Đã thanh toán {% else %} Chưa thanh toán {% endif %}</td>
    {% with state=order.state %}
    {% if state == '0' %}
    <td>Chờ xác nhận</td>
    {% elif state == '1' %}
    <td>Đã xác nhận</td>
    {% elif state == '2' %}
    <td>Đang giao hàng</td>
    {% elif state == '3' %}
    <td>Giao hàng thành công</td>
    {% elif state == '4' %}
    <td>Huỷ</td>
    {% elif state == '5' %}
    <td>Giao hàng thất bại</td>
    {% endif %}
    {% endwith %}
    <td>
      <a class="btn btn-primary" href="{% url 'orders:order_detail' order.id %}">Chi tiết</a>
    </td>
    {% if order.state == '0' %}
    <td>
      <a class="btn btn-danger" href="{% url 'orders:order_remove' order.id %}" 
      onclick="return confirm('Bạn có chắc muốn huỷ đơn hàng?');"> Huỷ đơn
      </a>
    </td>
    {% endif %}
    {% if order.state == '3' %}
    <td>
      <a class="btn btn-success" href="{% url 'orders:order_comment' order.id %}"> Đánh giá
      </a>
    </td>
    {% endif %}
  </tr>
  {% endfor %}
</table>
{% endif %}

{% endblock %}

templates/orders/order_list_admin.html
{% extends "shop/base.html" %}

{% block title %}
Cập nhật đơn hàng
{% endblock %}

{%block content %}
&nbsp;
{% if empty %}
<h1>Chưa có đơn hàng nào</h1>
{% else %}
<style>
  table {
    border-collapse: collapse;
    border-spacing: 0;
    width: 100%;
  }

  th, td {
    text-align: center;
    padding: 16px;
  }

  #myTable tr {
    border-bottom: 1px solid #ddd;
  }

  #myTable tr.header, #myTable tr:hover {
    background-color: #ccc;
  }
</style>

<table id="myTable">
  <tr class="header">
    <th>Ngày đặt đơn</th>
    <th>Họ tên</th>
    <th>Số điện thoại</th>
    <th>Địa chỉ 1</th>
    <th>Địa chỉ 2</th>
    <th>Tổng tiền</th>
    <th>Hình thức thanh toán</th>
    <th>Tình trạng thanh toán</th>
    <th>Trạng thái đơn hàng</th>
    <th style="width: 5%"></th>
  </tr>

  {% for order in orders.all %}
  <tr>
    <td>{{ order.created }}</td>
    <td>{{ order.user.profile.full_name }}</td>
    <td>{{ order.phone_number }}</td>
    <td>{{ order.user.profile.address }}</td>
    <td>{{ order.address_second }}</td>
    <td>{{ order.get_total_cost }} đ</td>
    <td>{% if order.payment_type == "1" %} Thanh toán bằng paypal {% else %} Thanh toán khi nhận hàng {% endif %}</td>
    <td>{% if order.paid %} Đã thanh toán {% else %} Chưa thanh toán {% endif %}</td>
    <td>
      <form action="{% url 'orders:order_change_state' order.id  %}">
        {% csrf_token %}
        <select name="order_state" onchange="this.form.submit()">
          <option value="0" {% if order.state == '0' %} selected {% endif %}>Chờ xác nhận</option>
          <option value="1" {% if order.state == '1' %} selected {% endif %}>Đã xác nhận</option>
          <option value="2" {% if order.state == '2' %} selected {% endif %}>Đang giao hàng</option>
          <option value="3" {% if order.state == '3' %} selected {% endif %}>Giao hàng thành công</option>
          <option value="4" {% if order.state == '4' %} selected {% endif %}>Huỷ</option>
          <option value="5" {% if order.state == '5' %} selected {% endif %}>Giao hàng thất bại</option>
        </select>
      </form>
    </td>
    <td>
      <a class="btn btn-primary" href="{% url 'orders:order_detail' order.id %}">Chi tiết</a>
    </td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% endblock %}

templates/orders/order_success.html
{% extends "shop/base.html" %}

{% block title %}
Đặt hàng thành công
{% endblock %}
&nbsp;
{% block content %}
	<h1>Đặt hàng thành công</h1>
{% endblock %}